version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '1234:80'
        volumes:
            - ./src/php:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '3306:80'
        environment:
            - PMA_ARBITRARY=1